NBAquiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve



urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'quizzes/', include('quizzes.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

] 

quizzes/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView




app_name = 'quizzes'
urlpatterns = [
	# ex: /quizzes/
	path('', views.IndexView.as_view(), name= 'index'),
	# ex: /quizzes/5/
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	# ex: /quizzes/5/results/
	path('<int:question_id>/vote/', views.vote, name= 'vote'),
	# ex: /quizzes/final_score/
	path('<int:pk>/final_score/', views.Final_ScoreView.as_view(), name= 'final_score'),

	



]

urlpatterns += staticfiles_urlpatterns() 

quizzes/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.urls import reverse


# Create your models here.
class Quiz(models.Model):
	name = models.CharField(max_length=1000)
	questions_count = models.IntegerField(default=0)
	description = models.IntegerField(default=0)
	created = models.DateTimeField(auto_now_add=True,null=True,blank=True)
	slug = models.SlugField()
	roll_out = models.BooleanField(default=False)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("vote", kwargs={"pk": self.pk})

class Meta:
	ordering = ['created',]
	verbose_name_plural = "Quizzes"
	db_table = 'Answer'

	def __str__(self):
		return self.name

class Question(models.Model):
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
	label = models.CharField(max_length=1000)
	order = models.IntegerField(default=0)
	pub_date = models.DateTimeField('date published')
	last_answer_time = models.DateTimeField(null=True)

	def __str__(self):
		return self.label

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

	def get_next(self):
		next = Question.objects.filter(id__gt=self.id).order_by('id').first()
		if next:
			return next
		else:
			return none


class Answer(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	text = models.CharField(max_length=1000)
	is_correct = models.BooleanField('Correct answer', default=False)

	def __str__(self):
		return self.text
		

### Save current score ###
class Scorer(models.Model):
	score = models.IntegerField(default=0)
	page = models.IntegerField()

quizzes/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.views.generic import TemplateView, ListView
from django.template.response import TemplateResponse


from flask import Flask, render_template
from .models import Quiz, Meta, Question, Answer, Scorer

# Create your views here.


### For homepage view ###
class IndexView(generic.ListView):
	template_name = 'quizzes/index.html'
	context_object_name = 'latest_question_list'

	
	
	def get_queryset(self):
		
		scorer, created = Scorer.objects.update_or_create(page=0)
		
		### To reset scores to 0 ###
		if Question.objects.filter(id=1):
			scorer.score = (scorer.score - scorer.score)
			scorer.save()

		"""Return the first published question """
		return Question.objects.filter(id=1)


### Each question's view ###
class DetailView(generic.DetailView):
	model = Question 
	template_name = 'quizzes/detail.html'




	def get_queryset(self):
		"""Return the last ten published questions (not including those set to be published in the future). """
		return Question.objects.filter(pub_date__lte=timezone.now())



	


### Results View ###
def vote(request, question_id, *args, **kwargs):
	model = Question
	template_name = 'quizzes/vote.html'
	question = get_object_or_404(Question, pk=question_id)

	### For template link to redirect ###
	first = Question.objects.get(pk=question_id)
	last = Question.objects.get(id=10)

	
	### To create user scoring system ###
	scorer, created = Scorer.objects.update_or_create(page=0)

	try:
		selected_choice = question.answer_set.get(pk=request.POST['answer'])


		### To save user score ###
		if selected_choice in Answer.objects.filter(id=1):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=6):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=12):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=13):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=19):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=22):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=28):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=30):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=36):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=37):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=38):
			scorer.score +=10
			scorer.save()

		if selected_choice in Answer.objects.filter(id=40):
			scorer.score += 10
			scorer.save()
			

		### For conditional background based on user selected answer ###
		context_dict = {}
		context_dict['selected_choice'] = str(selected_choice)
		context_dict['question'] = str(question)
		context_dict['score'] = str(scorer.score)
		context_dict['ans1'] = str(Answer.objects.get(id=1))
		context_dict['ans2'] = str(Answer.objects.get(id=6))
		context_dict['ans3'] = str(Answer.objects.get(id=12))
		context_dict['ans4'] = str(Answer.objects.get(id=13))
		context_dict['ans5'] = str(Answer.objects.get(id=19))
		context_dict['ans6'] = str(Answer.objects.get(id=22))
		context_dict['ans7'] = str(Answer.objects.get(id=28))
		context_dict['ans8'] = str(Answer.objects.get(id=30))
		context_dict['ans9'] = str(Answer.objects.get(id=36))
		context_dict['ans10'] = str(Answer.objects.get(id=37))
		context_dict['ans11'] = str(Answer.objects.get(id=38))
		context_dict['ans12'] = str(Answer.objects.get(id=40))

		
		context_dict['first'] = first
		context_dict['last'] = last


		### Passing a context dictionary from vote view to final_score view ###
		request.session['score'] = str(scorer.score)
		

	
	except (KeyError, Answer.DoesNotExist, ObjectDoesNotExist, MultipleObjectsReturned):
		pass

	# Redisplay the question voting form.
		return render(request, 'quizzes/detail.html', {'question': question })
	
	else:



		return render(request, 'quizzes/vote.html', context_dict)





### Final results once quiz is completed ###
class Final_ScoreView(generic.DetailView):
	model = Question
	template_name = 'quizzes/final_score.html'


	

quizzes/templates/quizzes/detail.html
 {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'quizzes/style1.css' %}">

<h1 style="color:Tomato; text-align:right; font-size:29px">{{ question.label }}</h1>


{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<div class = "myalignment">
<form style="text-align:right;" action="{% url 'quizzes:vote' question.id %}" method="post">
{% csrf_token %}
{% for answer in question.answer_set.all %}
	<input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}">
	<label style="color:White;" for ="answer{{ forloop.counter }}">{{ answer.text }}</label>
<br>
{% endfor %}

<br>
<input type="submit" value= "Submit Answer">
</form>
</div>



<html>
<head>
<style>
.myalignment {
	display: inline-block;
	float: right;
	text-align: left;
	font-size: 20px;
}
</style>
</head>
<body>

quizzes/templates/quizzes/final_score.html
 {% load static %}

<head>
		<link rel="stylesheet" type="text/css" href="{% static 'quizzes/style.css' %}">
	</head>

	<body>
		<p style="color:gold;font-size: 30px;text-align: left;"><b>Thank you for playing!<br> 
		FINAL SCORE: {{ request.session.score }}% out of 100%<b>
		</p>

		<p style="color:Navy;font-size: 16px;text-align: left;">
		Correct Answers:
		<br>
		<br>
		1) James Harden - Points Per Game (PPG) leader for the 2019/2020 season
		<br>
		<br>
		2) Lebron James - Assists Per Game (APG) leader for the 2019/2020 season 
		<br>
		<br>
		3) Andre Drummond - Rebounds Per Game (RPG) leader for the 2019/2020 season
		<br>
		<br>
		4) Ben Simmons - Steals Per Game (SPG) leader for the 2019/2020 season
		<br>
		<br>
		5) Hassan Whiteside - Blocks Per Game (BPG) leader for the 2019/2020 season
		<br>
		<br>
		6) Sekou Doumbouya - youngest active player in the NBA for 2019/2020 season
		<br>
		<br>
		7) Vince Carter - oldest active player in the NBA for 2019/2020 season
		<br>
		<br>
		8) Tacko Fall - tallest active player in the NBA for 2019/2020 season
		<br>
		<br>
		9) Giannis Antetokounmpo - foreign active NBA player has the most Points Per Game for the 2019/2020 season
		<br>
		<br>
		10) Michael Jordan - subjectively the Greatest Player of All-Time (GOAT)

		</p>
	</body>

	<br>
	<a href ="{% url 'quizzes:index' %}"; style= 'font-size: 30px; color:gold;'> Retake Quiz! </a>

quizzes/templates/quizzes/index.html
{% load static %}

<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static 'quizzes/style.css' %}">
	</head>

	<body>


		<h style="color:gold;font-size: 50px;text-align: justify;"><b>NBA QUIZ - 2019/2020 Season</b></h>

		<h2 style="color:gold;font-size: 24px;text-align: left;"><br/>Welcome to a true test of your NBA statistical knowledge! <br/> Do NOT click your back button for accurate scoring <br/> The passing score is 80% </h2>

		{% if latest_question_list %}
			<ul>{% for question in latest_question_list %}
				<br/><li><a href="{% url 'quizzes:detail' question.id %}" style="font-size: 20px">CLICK TO BEGIN </a></li>
			{% endfor %}</ul>

		{% else %}
			<p>No quizzes are available.</p>	
		{% endif %}
		
		
		
	
	


		







	</body>
</html>

quizzes/templates/quizzes/vote.html
{% load static %} 

<html>
	<head>	
		<link rel="stylesheet" type="text/css" href="{% static 'quizzes/style2.css' %}">
	</head>


	
{% if selected_choice == ans1 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct1">
{% elif selected_choice == ans2 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct2">
{% elif selected_choice == ans3 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct3">
{% elif selected_choice == ans4 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct4">
{% elif selected_choice == ans5 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct5">
{% elif selected_choice == ans6 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct6">
{% elif selected_choice == ans7 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct7">
{% elif selected_choice == ans8 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct8">
{% elif selected_choice == ans9 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct9">
{% elif selected_choice == ans10 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct10">
{% elif selected_choice == ans11 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct11">
{% elif selected_choice == ans12 %}
	<h1 class="customtextcorrect">Correct! Good job.</h1>
	<body class= "correct12">
{% else %} 
	<h1 class="customtextwrong">Wrong!! Please proceed to the next question.</h1>
	<body class="wrong"> 
{% endif %}
	
	

	

<p style="color:white;font-size: 24px;text-align: left;"> 
Current Score: {{ score }}% out of 100%
</p>



{% with next=first.get_next_by_pub_date %}
	{% if next %}
		<a href ="{% url 'quizzes:detail' next.id %}"; style= 'font-size: 20px; color:white;'> Next Question </a>
	{% else %}
		<a href ="{% url 'quizzes:final_score' last.id %}"; style= 'font-size: 20px; color:white;'> Next Question </a>
	{% endif %}
{% endwith %}








	




		</body>

</html>